# Generated by Django 4.2.7 on 2026-04-23 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分类编码')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='图标')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工具分类',
                'verbose_name_plural': '工具分类',
                'db_table': 'common_tool_categories',
                'ordering': ['sort', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommonToolTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('color', models.CharField(blank=True, default='', max_length=20, verbose_name='标签颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工具标签',
                'verbose_name_plural': '工具标签',
                'db_table': 'common_tool_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommonToolResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='资源名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='资源编码')),
                ('type', models.CharField(choices=[('tool_link', '工具链接'), ('website', '网站地址'), ('doc_link', '文档链接'), ('mock_platform', 'Mock平台'), ('env_address', '环境地址'), ('memo', '备忘信息'), ('faq', 'FAQ'), ('other', '其他')], max_length=20, verbose_name='资源类型')),
                ('icon', models.CharField(blank=True, default='', max_length=100, verbose_name='图标')),
                ('short_desc', models.CharField(blank=True, default='', max_length=500, verbose_name='简介')),
                ('content', models.TextField(blank=True, default='', verbose_name='使用说明/内容')),
                ('url', models.URLField(blank=True, default='', max_length=500, verbose_name='访问地址')),
                ('open_mode', models.CharField(choices=[('_blank', '新窗口打开'), ('_self', '当前窗口打开'), ('internal', '站内查看')], default='_blank', max_length=20, verbose_name='打开方式')),
                ('env_type', models.CharField(blank=True, choices=[('dev', '开发环境'), ('test', '测试环境'), ('staging', '预发环境'), ('prod', '生产环境'), ('', '不涉及')], default='', max_length=20, verbose_name='环境类型')),
                ('owner_name', models.CharField(blank=True, default='', max_length=100, verbose_name='负责人')),
                ('owner_contact', models.CharField(blank=True, default='', max_length=200, verbose_name='联系方式')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('visibility_type', models.CharField(choices=[('public', '所有人可见'), ('team', '团队可见'), ('private', '仅自己可见')], default='public', max_length=20, verbose_name='可见范围')),
                ('extra_json', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('access_count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='common_tools.commontoolcategory', verbose_name='分类')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_common_tools', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('tags', models.ManyToManyField(blank=True, related_name='resources', to='common_tools.commontooltag', verbose_name='标签')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_common_tools', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '工具资源',
                'verbose_name_plural': '工具资源',
                'db_table': 'common_tool_resources',
                'ordering': ['-is_top', 'sort', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CommonToolAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('access_type', models.CharField(default='view', help_text='view=查看, click=点击链接', max_length=20, verbose_name='访问类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='common_tools.commontoolresource', verbose_name='资源')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='访问用户')),
            ],
            options={
                'verbose_name': '访问记录',
                'verbose_name_plural': '访问记录',
                'db_table': 'common_tool_access_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commontoolresource',
            index=models.Index(fields=['type'], name='common_tool_type_90f207_idx'),
        ),
        migrations.AddIndex(
            model_name='commontoolresource',
            index=models.Index(fields=['category'], name='common_tool_categor_a39efc_idx'),
        ),
        migrations.AddIndex(
            model_name='commontoolresource',
            index=models.Index(fields=['is_enabled'], name='common_tool_is_enab_611a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='commontoolresource',
            index=models.Index(fields=['is_recommend'], name='common_tool_is_reco_0d73b8_idx'),
        ),
        migrations.AddIndex(
            model_name='commontoolaccesslog',
            index=models.Index(fields=['resource', '-created_at'], name='common_tool_resourc_63050b_idx'),
        ),
        migrations.AddIndex(
            model_name='commontoolaccesslog',
            index=models.Index(fields=['user', '-created_at'], name='common_tool_user_id_76461b_idx'),
        ),
    ]
